---
title: "viz"
author: "Seba Tapia"
date: "April 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scatterplot

```{r load libraries, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(gapminder)

# preview data
gapminder

# get range of available data
summary(gapminder)
```

```{r, warning=FALSE, message=FALSE}
# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  geom_point()
s
s + geom_smooth() +aes(size=pop) + aes(color=continent)

ggsave('HealthWealth.png')  #it takes the last one you made. You can also specify the one you want
```

#MAPS
```{r maps}
#install.packages('tmap')
library(tmap)

# load world spatial polygons
data(World)

# inspect values in World
World@data %>% tbl_df()

# gapminder countries not in World. skipping for now
g %>% 
  anti_join(World@data, by=c('country'='name')) %>% 
  arrange(desc(pop))

# World countries not in gapminder. skipping for now
World@data %>% 
  anti_join(g, by=c('name'='country')) %>% 
  arrange(desc(pop_est)) %>%
  select(iso_a3, name, pop_est)

# join gapminder data to World. The variable values by which you join have to match
World@data = World@data %>%
  left_join(g, by=c('name'='country'))
```

## Make map
```{r make map}
# make map
m = tm_shape(World) +
    tm_polygons('lifeExp', palette='RdYlGn', id='name', title='Life expectancy (years)', auto.palette.mapping=F) +
    tm_style_gray() + tm_format_World()
m
```


## Interactive map

```{r interactive map}

# show interactive map
tmap_leaflet(m)

```

